spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authcore
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/auth-core
          jwk-set-uri: http://localhost:8085/realms/auth-core/protocol/openid-connect/certs
app:
  core:
    environment: local