server:
  servlet:
    context-path: ${CONTEXT_PATH}
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
  application:
    name: core
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          jwk-set-uri: ${AUTH_JWK_SET_URI}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
app:
  core:
    environment: ${CORE_ENVIRONMENT}